// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuxwpoknhlizefjsqxdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51eHdwb2tuaGxpemVmanNxeGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NzE4ODEsImV4cCI6MjA4NzM0Nzg4MX0.AcYN8Bh9qtGv8ze1HxvjTs8Y6DfELNwDhOT0d9BDMG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});